spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kpi
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret: SomeVeryVeryVeryVeryVeryVeryVerySecretJwtSecretKey
  access-token-ttl-ms: 300000
  refresh-token-ttl-ms: 2592000000